### ISSUE TITLE
CIM ORG content is weg gevallen

### ISSUE THREAD

**Issue by ahornickel** [Geonovum/dso-cim-ex#1]
na de laatste update is de content van het CIM ORG niet raadpleegbaar (404), Gisteren lukte dat nog wel

**Comment by wilkoquak** [comment]
Gefixed. Ik was bezig de catalogus op een nette manier te publiceren. Maar dat zit nog aardig wat werk aan. Daardoor was er even geen werkversie.

**Comment by ahornickel** [comment]
Top 👍 En goed te zien dat de issue tracking goed werkt ;-)

**Comment by ahornickel** [comment]
ah, zie de teksten idd weer. alleen het model zelf nog niet :-|

**Comment by wilkoquak** [comment]
Ook dat is nu gefixed. Diagrammen worden alleen getoond hun naam eindigt op '- overzicht' of op '- detail'. dat heb ik nu weer toegevoegd. In ieder geval in mijn kopie.
